Repository ibexa/twig-components, pull requests merged in 2025-05, with the labels that each got.

#7 IBX-8471: Upgraded codebase to Symfony 7
  composer.json
Labels: Ready for SF7

#9 IBX-9697: Setters to parameters in events added
  src/bundle/Resources/views/profiler/panel.html.twig
  src/contracts/Event/RenderGroupEvent.php
  src/contracts/Event/RenderSingleEvent.php
Labels: Ready for review

#13 Allowed adding runtime parameters in TemplateComponent
  src/lib/Component/TemplateComponent.php
  tests/bundle/Component/TemplateComponentTest.php
Labels: Improvement, Ready for review
